name: Notify via Webhook

on:
  workflow_call:
    inputs:
      commit_author:
        type: string
        description: "The author of the commit"
        required: true
      commit_email:
        type: string
        description: "The email of the commit author"
        required: true
      linux_build_status:
        type: string
        description: "The linux build status"
        required: true
      windows_build_status:
        type: string
        description: "The windows build status"
        required: true
      macos_build_status:
        type: string
        description: "The macos build status"
        required: true
      format_updated:
        type: string
        description: "The format updated status"
        required: true
      docs_updated:
        type: string
        description: "The docs updated status"
        required: true
      tests_status:
        type: string
        description: "The tests status"
        required: true
      coverage_value:
        type: string
        description: "The coverage value"
        required: true
      branches_coverage_value:
        type: string
        description: "The branches coverage value"
        required: true

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the values to set the badges
        run: |
          LINUX_BUILD_STATUS="${{ inputs.linux_build_status }}"
          WINDOWS_BUILD_STATUS="${{ inputs.windows_build_status }}"
          MACOS_BUILD_STATUS="${{ inputs.macos_build_status }}"
          FORMAT_UPDATED="${{ inputs.format_updated }}"
          DOCS_UPDATED="${{ inputs.docs_updated }}"
          TESTS_STATUS="${{ inputs.tests_status }}"
          COVERAGE_VALUE="${{ inputs.coverage_value }}"
          BRANCHES_COVERAGE_VALUE="${{ inputs.branches_coverage_value }}"

          LINUX_BUILD_STATUS=$(echo "${LINUX_BUILD_STATUS}" | sed 's/ /%20/g')
          WINDOWS_BUILD_STATUS=$(echo "${WINDOWS_BUILD_STATUS}" | sed 's/ /%20/g')
          MACOS_BUILD_STATUS=$(echo "${MACOS_BUILD_STATUS}" | sed 's/ /%20/g')
          FORMAT_UPDATED=$(echo "${FORMAT_UPDATED}" | sed 's/ /%20/g')
          DOCS_UPDATED=$(echo "${DOCS_UPDATED}" | sed 's/ /%20/g')
          TESTS_STATUS=$(echo "${TESTS_STATUS}" | sed 's/ /%20/g')
          COVERAGE_VALUE=$(echo "${COVERAGE_VALUE}" | sed 's/ /%20/g' | sed 's/%/%25/g')
          BRANCHES_COVERAGE_VALUE=$(echo "${BRANCHES_COVERAGE_VALUE}" | sed 's/ /%20/g' | sed 's/%/%25/g')

          curl -o ./.github/Badges/linux-build.svg "https://img.shields.io/badge/Linux-${LINUX_BUILD_STATUS}-blue"
          curl -o ./.github/Badges/windows-build.svg "https://img.shields.io/badge/Windows-${WINDOWS_BUILD_STATUS}-blue"
          curl -o ./.github/Badges/macos-build.svg "https://img.shields.io/badge/MacOS-${MACOS_BUILD_STATUS}-blue"
          curl -o ./.github/Badges/format-updated.svg "https://img.shields.io/badge/Formating-${FORMAT_UPDATED}-blue"
          curl -o ./.github/Badges/docs-updated.svg "https://img.shields.io/badge/Documentation-${DOCS_UPDATED}-blue"
          curl -o ./.github/Badges/tests-status.svg "https://img.shields.io/badge/Tests-${TESTS_STATUS}-blue"
          curl -o ./.github/Badges/coverage-value.svg "https://img.shields.io/badge/Coverage-${COVERAGE_VALUE}-blue"
          curl -o ./.github/Badges/branches-coverage-value.svg "https://img.shields.io/badge/Branches-${BRANCHES_COVERAGE_VALUE}-blue"

      - name: Config Git
        run: |
          git pull
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit & Push changes
        run: |
          git add . || true
          git commit -m "[CI] - [BADGES] - The status badges have been updated" || true
          git commit --amend --author="${{ inputs.commit_author }} <${{ inputs.commit_email }}>" -m "[CI] - [BADGES] - The status badges have been updated" || true
          git push origin main || exit 0
