name: Linux CMake Build Checker

on:
  workflow_call:
    outputs:
      LINUX_BUILD_STATUS:
        description: "The status of the build"
        value: ${{ jobs.build-linux.outputs.LINUX_BUILD_STATUS }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      LINUX_BUILD_STATUS: ${{ env.LINUX_BUILD_STATUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull any modifications
        run: git pull

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build project
        run: |
          mkdir Build/
          cd Build/
          cmake ..
          cmake --build .
          cd ..
        continue-on-error: true

      - name: Get Build Status
        run: |
          if [[ $? -eq 0 ]]; then
            echo "LINUX_BUILD_STATUS=LINUX BUILD OK" >> $GITHUB_ENV
          else
            echo "LINUX_BUILD_STATUS=LINUX BUILD KO" >> $GITHUB_ENV
          fi
        continue-on-error: true
