name: MacOS CMake Build Checker

on:
  workflow_call:
    outputs:
      MACOS_BUILD_STATUS:
        description: "The status of the build"
        value: ${{ jobs.build-macos.outputs.MACOS_BUILD_STATUS }}

jobs:
  build-macos:
    runs-on: macos-latest
    outputs:
      MACOS_BUILD_STATUS: ${{ env.MACOS_BUILD_STATUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull any modifications
        run: git pull

      - name: Echo Hello World
        run: echo "Hello World"

      #   - name: Install CMake
      #     run: |
      #       brew install cmake

      #   - name: Build project
      #     run: |
      #       mkdir Build/
      #       cd Build/
      #       cmake ..
      #       cmake --build .
      #       cd ..
      #     continue-on-error: true

      - name: Get Build Status
        shell: pwsh
        run: |
          if ($?) {
            echo "MACOS_BUILD_STATUS=OK" >> $env:GITHUB_ENV
          } else {
            echo "MACOS_BUILD_STATUS=ERROR" >> $env:GITHUB_ENV
          }
