name: Windows CMake Build Checker

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      BUILD_STATUS: ${{ steps.get_build_status.outputs.BUILD_STATUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

      - name: Build project
        run: |
          mkdir Build/
          cd Build/
          cmake ..
          cmake --build .
          cd ..
        continue-on-error: true

      - name: Get Build Status
        id: get_build_status
        run: |
          if [[ $? -eq 0 ]]; then
            echo "::set-output name=BUILD_STATUS::WINDOWS BUILD OK"
          else
            echo "::set-output name=BUILD_STATUS::WINDOWS BUILD KO"
          fi
        continue-on-error: true
