name: Windows CMake Build Checker

on:
  workflow_call:
    outputs:
      WINDOWS_BUILD_STATUS:
        description: "The status of the build"
        value: ${{ jobs.build-windows.outputs.WINDOWS_BUILD_STATUS }}

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      WINDOWS_BUILD_STATUS: ${{ env.WINDOWS_BUILD_STATUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

      - name: Build project
        run: |
          mkdir Build/
          cd Build/
          cmake ..
          cmake --build .
          cd ..
        continue-on-error: true

      - name: Get Build Status
        run: |
          if [[ $? -eq 0 ]]; then
            echo "WINDOWS_BUILD_STATUS=WINDOWS BUILD OK" >> $GITHUB_ENV
          else
            echo "WINDOWS_BUILD_STATUS=WINDOWS BUILD KO" >> $GITHUB_ENV
          fi
        continue-on-error: true
