name: Clang Code Formatter

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest
    outputs:
      UPDATED: ${{ steps.get_updated_status.outputs.UPDATED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ClangFormat
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Format code
        run: |
          find . -type f -name "*.cpp" -o -name "*.hpp" | while read file; do
            clang-format -i $file
          done

      - name: Get Updated Status
        id: get_updated_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::set-output name=UPDATED::DOCS UPDATED"
          else
            echo "::set-output name=UPDATED::DOCS NOT UPDATED"
          fi
        continue-on-error: true

      - name: Update GitHub Actions Log
        run: |
          echo "Code formatting completed successfully!" >> ./.github/GithubActionsLogs.txt
          date "+%Y-%m-%d %H:%M:%S" >> ./.github/GithubActionsLogs.txt

      - name: Commit & Push changes
        run: |
          git add . || true
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "[CI] - [FORMAT] - Format Checked/Updated" || true
          git push origin main || true
