name: Clang Code Formatter

on:
  workflow_call:
    outputs:
      UPDATED:
        description: "The status of the code formatting"
        value: ${{ jobs.format-code.outputs.UPDATED }}
    inputs:
      commit_author:
        type: string
        description: "The author of the commit"
        required: true
      commit_email:
        type: string
        description: "The email of the commit author"
        required: true

jobs:
  format-code:
    runs-on: ubuntu-latest
    outputs:
      UPDATED: ${{ steps.get_updated_status.outputs.UPDATED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ClangFormat
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Format code
        run: |
          find . -type f -name "*.cpp" -o -name "*.hpp" | while read file; do
            clang-format -i $file
          done

      - name: Get Updated Status
        id: get_updated_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "UPDATED=FORMATTED" >> $GITHUB_ENV
          else
            echo "UPDATED=NOT FORMATTED" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Update GitHub Actions Log
        run: |
          echo "Code formatting completed successfully!" >> ./.github/GithubActionsLogs.txt
          date "+%Y-%m-%d %H:%M:%S" >> ./.github/GithubActionsLogs.txt

      - name: Commit & Push changes
        run: |
          git add . || true
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "[CI] - [FORMAT] - Format Checked/Updated" || true
          git commit --amend --author="${{ inputs.commit_author }} <${{ inputs.commit_email }}>" || true
          git push origin main || true
