name: Clang Code Formatter

on:
  workflow_call:
    outputs:
      FORMAT_UPDATED:
        description: "The status of the code formatting"
        value: ${{ jobs.format-code.outputs.FORMAT_UPDATED }}
    inputs:
      commit_author:
        type: string
        description: "The author of the commit"
        required: true
      commit_email:
        type: string
        description: "The email of the commit author"
        required: true

jobs:
  format-code:
    runs-on: ubuntu-latest
    outputs:
      FORMAT_UPDATED: ${{ env.FORMAT_UPDATED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ClangFormat
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Format code
        run: |
          find . -type f -name "*.cpp" -o -name "*.hpp" | while read file; do
            clang-format -i $file
          done

      - name: Get Format Update Status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "FORMAT_UPDATED=FORMATTED" >> $GITHUB_ENV
          else
            echo "FORMAT_UPDATED=NOT FORMATTED" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Config Git
        run: |
          git pull
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit & Push changes
        run: |
          git add . || true
          git commit -m "[CI] - [FORMAT] - The code has been formatted" || true
          git commit --amend --author="${{ inputs.commit_author }} <${{ inputs.commit_email }}>" -m "[CI] - [FORMAT] - The code has been formatted" || true
          git push origin main || exit 0
