name: Code Formatter

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ClangFormat
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Format code
        run: |
          find . -type f -name "*.cpp" -o -name "*.hpp" | while read file; do
            clang-format -i $file
          done

      - name: Commit changes
        run: |
          git add . || true
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "[CI] - [FORMAT] - Formatting Code" || true

      - name: Update commit metadatas
        run: |
          git commit --amend --author="$COMMIT_AUTHOR <$COMMIT_EMAIL>" -m "[CI] - [FORMAT] - Formatting Code" || true

      - name: Push to GitHub
        run: |
          git push origin main || true
