name: Doxygen Documentation Updater

on:
  workflow_call:
    outputs:
      DOCS_UPDATED:
        description: "The status of the code formatting"
        value: ${{ jobs.update_documentations.outputs.DOCS_UPDATED }}
    inputs:
      commit_author:
        type: string
        description: "The author of the commit"
        required: true
      commit_email:
        type: string
        description: "The email of the commit author"
        required: true

jobs:
  update_documentations:
    runs-on: ubuntu-latest
    outputs:
      DOCS_UPDATED: ${{ env.DOCS_UPDATED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packages List
        run: |
          sudo apt-get update

      - name: Set up Doxygen
        run: |
          sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: |
          doxygen Documentations/Doxyfile

      - name: Get Documentations Update Status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "DOCS_UPDATED=UPDATED" >> $GITHUB_ENV
          else
            echo "DOCS_UPDATED=NOT UPDATED" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Config Git
        run: |
          git pull
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit & Push changes
        run: |
          git add . || true
          git commit -m "[CI] - [DOCS] - The documentation has been updated"  || true
          git commit --amend --author="${{ inputs.commit_author }} <${{ inputs.commit_email }}>" -m "[CI] - [DOCS] - The documentation has been updated"  || true
          git push origin main || exit 0
