name: Doxygen Documentation Updater

on:
  workflow_call:
    outputs:
      UPDATED:
        description: "The status of the documentation update"
        value: ${{ jobs.update_documentations.outputs.UPDATED }}
    inputs:
      commit_author:
        type: string
        description: "The author of the commit"
        required: true
      commit_email:
        type: string
        description: "The email of the commit author"
        required: true

jobs:
  update_documentations:
    runs-on: ubuntu-latest
    outputs:
      UPDATED: ${{ steps.get_updated_status.outputs.UPDATED }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packages List
        run: |
          sudo apt-get update

      - name: Set up Doxygen
        run: |
          sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: |
          doxygen Docs/Doxyfile

      - name: Get Updated Status
        id: get_updated_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "UPDATED=DOCS UPDATED" >> $GITHUB_ENV
          else
            echo "UPDATED=DOCS NOT UPDATED" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Update GitHub Actions Log
        run: |
          echo "Doxygen Documentation Generation completed successfully!" >> ./.github/GithubActionsLogs.txt
          date "+%Y-%m-%d %H:%M:%S" >> ./.github/GithubActionsLogs.txt

      - name: Commit & Push changes
        run: |
          git add . || true
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "[CI] - [DOCS] - Documentation Checked/Updated" || true
          echo "Commit Author: ${{ inputs.commit_author }}"
          echo "Commit Email: ${{ inputs.commit_email }}"
          git commit --amend --author="${{ inputs.commit_author }} <${{ inputs.commit_email }}>" || true
          git push origin main || true
