name: Doxygen Documentation Updater

on:
  workflow_run:
    workflows: ["Code Formatter"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update_documentations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packages List
        run: sudo apt-get update

      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: |
          doxygen Docs/Doxyfile

      - name: Commit changes
        run: |
          git add . || true
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "[CI] - [FORMAT] - Formatting Code" || true

      - name: Update commit metadatas
        run: |
          git commit --amend --author="$COMMIT_AUTHOR <$COMMIT_EMAIL>" -m "[CI] - [FORMAT] - Formatting Code" || true

      - name: Push to GitHub
        run: |
          git push origin main || true
