name: Template CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  CommitMetadataGetter:
    uses: ./.github/workflows/CommitMetadataGetter.yml

  ClangCodeFormatter:
    needs: CommitMetadataGetter
    uses: ./.github/workflows/ClangCodeFormatter.yml
    with:
      commit_author: ${{ needs.CommitMetadataGetter.outputs.COMMIT_AUTHOR }}
      commit_email: ${{ needs.CommitMetadataGetter.outputs.COMMIT_EMAIL }}


  DocumentationUpdater:
    needs: ["CommitMetadataGetter", "ClangCodeFormatter"]
    uses: ./.github/workflows/DocumentationUpdater.yml
    with:
      commit_author: ${{ needs.CommitMetadataGetter.outputs.COMMIT_AUTHOR }}
      commit_email: ${{ needs.CommitMetadataGetter.outputs.COMMIT_EMAIL }}

  BuildCheckerLinux:
    needs: ["CommitMetadataGetter", ClangCodeFormatter, "DocumentationUpdater"]
    uses: ./.github/workflows/BuildCheckerLinux.yml

  BuildCheckerWindows:
    needs: ["CommitMetadataGetter", ClangCodeFormatter, "DocumentationUpdater"]
    uses: ./.github/workflows/BuildCheckerWindows.yml
