name: Template CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  CommitMetadataGetter:
    uses: ./.github/workflows/CommitMetadataGetter.yml

  ClangCodeFormatter:
    needs: CommitMetadataGetter
    uses: ./.github/workflows/ClangCodeFormatter.yml

  DocumentationUpdater:
    needs: ClangCodeFormatter
    uses: ./.github/workflows/DocumentationUpdater.yml

  BuildCheckerLinux:
    needs: ClangCodeFormatter
    uses: ./.github/workflows/BuildCheckerLinux.yml

  BuildCheckerWindows:
    needs: ClangCodeFormatter
    uses: ./.github/workflows/BuildCheckerWindows.yml
