name: Notify via Webhook

on:
  workflow_call:
    inputs:
      webhook_field:
        type: string
        description: "The webhook field"
        required: true
      webhook:
        type: string
        description: "The webhook to send the message to"
        required: true
      message_file:
        type: string
        description: "The message file path"
        required: true
      commit_message:
        type: string
        description: "The commit message"
        required: true
      commit_author:
        type: string
        description: "The commit author"
        required: true
      commit_email:
        type: string
        description: "The commit email"
        required: true
      commit_hash:
        type: string
        description: "The commit hash"
        required: true
      commit_date:
        type: string
        description: "The commit date"
        required: true
      linux_build_status:
        type: string
        description: "The linux build status"
        required: true
      windows_build_status:
        type: string
        description: "The windows build status"
        required: true
      macos_build_status:
        type: string
        description: "The macos build status"
        required: true
      format_updated:
        type: string
        description: "The format updated status"
        required: true
      docs_updated:
        type: string
        description: "The docs updated status"
        required: true
      tests_status:
        type: string
        description: "The tests status"
        required: true
      coverage_value:
        type: string
        description: "The coverage value"
        required: true
      branches_coverage_value:
        type: string
        description: "The branches coverage value"
        required: true
      repository_url:
        type: string
        description: "The repository url"
        required: true
      pipeline_url:
        type: string
        description: "The pipeline url"
        required: true

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and format message
        id: format_message
        run: |
          MESSAGE=$(cat ${{ inputs.message_file }})
          FORMATTED_MESSAGE=$(echo "$MESSAGE" | sed "s|{{COMMIT_MESSAGE}}|${{ inputs.commit_message }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{COMMIT_AUTHOR}}|${{ inputs.commit_author }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{COMMIT_EMAIL}}|${{ inputs.commit_email }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{COMMIT_HASH}}|${{ inputs.commit_hash }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{COMMIT_DATE}}|${{ inputs.commit_date }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{LINUX_BUILD_STATUS}}|${{ inputs.linux_build_status }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{WINDOWS_BUILD_STATUS}}|${{ inputs.windows_build_status }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{MACOS_BUILD_STATUS}}|${{ inputs.macos_build_status }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{FORMAT_UPDATED}}|${{ inputs.format_updated }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{DOCS_UPDATED}}|${{ inputs.docs_updated }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{TESTS_STATUS}}|${{ inputs.tests_status }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{COVERAGE_VALUE}}|${{ inputs.coverage_value }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{BRANCHES_COVERAGE_VALUE}}|${{ inputs.branches_coverage_value }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{REPOSITORY_URL}}|${{ inputs.repository_url }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed "s|{{PIPELINE_URL}}|${{ inputs.pipeline_url }}|g")
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | jq -Rsa .)
          FORMATTED_MESSAGE=$(echo "$FORMATTED_MESSAGE" | sed 's|\"|\\\"|g')
          echo "FORMATTED_MESSAGE=$FORMATTED_MESSAGE" >> $GITHUB_ENV

      - name: Notify Via Webhook
        run: |
          curl -X POST -H 'Content-Type: application/json' -d "{\"${{ inputs.webhook_field }}\":${{ env.FORMATTED_MESSAGE }}}" ${{ inputs.webhook }}
